### ISSUE TITLE
make turret follow speaker tag

### ISSUE THREAD

**Issue by ryanabraham1** [Team3256/Kirby_Bot_2024#28]

**Comment by ThatXliner** [comment]
Do we not have https://github.com/Team3256/Kirby_Bot_2024/blob/6cc52511c06af2c2b715552fd75ae7e2711c33c4/src/main/java/frc/robot/subsystems/turret/Turret.java#L113 already?

**Comment by ryanabraham1** [comment]
make it work irl i assume it just doesn't immediately begin to work
